---
title: "东莞二手房交易数据"
output: html_document
outdir: '/home/www'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r message=FALSE, include=FALSE}

.libPaths("/home/yusen/R/x86_64-redhat-linux-gnu-library/3.5")
# read csv file
library(readr)
library(dplyr)
library(lubridate)

start_date = ymd('2019-07-15')
days = today() - start_date
day_range <- c(days:1)
today() - day_range -> day_range
paste0('data/',day_range, '.csv') -> file_path

price_df_all <- data.frame()
for(i in 1: days){
  if(file.exists(file_path[i])){
    price_df <- read_csv(file = file_path[i])
    price_df <- price_df %>% mutate(date = day_range[i])
    
    price_df_all <- bind_rows(price_df_all, price_df)
  }
}

price_df_all <- price_df_all %>% na_if(0)

price_df_all %>% mutate(`日平均单位面积金额（万元）` = `当日成交金额（万元）` / `当日成交面积（㎡）`,
                    日平均单套金额 = `当日成交金额（万元）` / `当日签约（套）`,
                    周 = isoweek(date),
                    月 = month(date),
                    季度 = quarter(date),
                    年 = isoyear(date)) -> price_df_all

```

东莞二手房交易每日数数据，  

开始日期：2019-07-15  
最新日期：`r max(price_df_all$date)`  


各镇区累计销售指标比较  

```{r echo=FALSE}
library(radarchart)

price_df_all %>% 
  group_by(镇区) %>%
  summarise(总套数 = sum(`当日签约（套）`, na.rm = TRUE),
               总金额 = sum(`当日成交金额（万元）`, na.rm = TRUE),
               总面积 = sum(`当日成交面积（㎡）`, na.rm = TRUE),
               单价 = if_else(总面积 == 0 , 0, 总金额/总面积),
               套价 = if_else(总套数 == 0, 0, 总金额/总套数),
               有成交日数 = sum(if_else(is.na(`当日成交金额（万元）`),0,1))
               ) %>% 
  ungroup() %>%
  mutate_if(is.numeric,.funs = function(x){x / max(x,na.rm = TRUE)}) -> area


colnames <- area$镇区
labs <- area %>% select(-镇区) %>% colnames()


area %>% select(-镇区) %>%
  t() %>%
  as.data.frame() -> area

colnames(area) <- colnames
area <-cbind(labs,area)

chartJSRadar(area,  maxScale = 1, showToolTipLabel=TRUE)
```





```{r echo=FALSE}
library(rpivotTable)

rpivotTable(price_df_all,
            rows = '镇区',
            cols = c('年', '月'),
            aggregatorName = 'Sum over Sum',
            vals = c('当日成交金额（万元）', '当日成交面积（㎡）'))
```



















